version: '3'
services:
  base:
    image: jerasin/base-angular-nest:1.0
    build: 
      context: .
      dockerfile: docker/base.Dockerfile
      target: base-stage
    command: /bin/true
  api:
    build:
      context: .
      dockerfile: docker/api.dev.Dockerfile
      target: runtime-stage
    container_name: api 
    env_file:
    - .env
    depends_on:
      - base
    # ports:
    #   - 3333:3333
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./libs:/app/libs
      - ./logs:/app/logs
  web:
    build:
      context: .
      dockerfile: docker/web.dev.Dockerfile
      target: runtime-stage
    container_name: web
    restart: on-failure
    # ports:
    #   - 4200:4200
    volumes:
      - ./apps/bookstore/src:/app/apps/bookstore/src
    depends_on:
      - base
      - api
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dev.Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 4200:4200
      - 3333:3333
      - 8090:8080
    depends_on:
      - api
